import Head from "next/head";
import Link from "next/link";

import axios from "configs/axios";

function Home(props) {
   return (
      <div className="container mx-auto mt-4">
         <Head>
            <title>Hello</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <main>
            <h1>Saya Halaman Utama</h1>
            <Link href="/random">
               <a>Bring me to random fetch</a>
            </Link>
         </main>
      </div>
   );
}

Home.getInitialProps = async () => {
   try {
      const data = await axios.get("/courses");
      return { data: data.data.data };
   } catch (error) {}
};

export default Home;
