import Head from "next/head";
import Link from "next/link";

import axios from "src/configs/axios";

import Header from "src/parts/Header";
function Home({ data }) {
   return (
      <>
         <Head>
            <title>Hello</title>
            <meta name="description" content="Generated by create next app" />
         </Head>

         <main>
            <section className="header-clipping pt-10">
               <img
                  src={`${process.env.NEXT_PUBLIC_BASE_URL}/images/circle.svg`}
                  alt=""
                  className="absolute left-0 bottom-0"
               />
               <div className="sunshine"></div>
               <div className="container mx-auto">
                  <Header onLight></Header>
               </div>
            </section>
         </main>
      </>
   );
}

Home.getInitialProps = async () => {
   try {
      const data = await axios.get("/courses");
      return { data: data.data.data };
   } catch (error) {}
};

export default Home;
